on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test
  build:
    name: Build
    runs-on: ubuntu-24.04
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          path: target/release/checksum-util
  release:
    name: Release
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: target/release/checksum-util
