on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test

  build-and-release:
    name: Build and upload
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-22.04
            target: x86_64-unknown-linux-musl
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
          - build: macos
            os: macos-latest
            target: aarch64-apple-darwin
          # - build: windows-gnu
          #   os: windows-latest
          #   target: x86_64-pc-windows-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=$(git describe --always)" >> $GITHUB_ENV
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --verbose --release --target ${{ matrix.target }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: checksum-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/checksum
      - name: Build archive
        shell: bash
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          binary_name="checksum"
          dirname="$binary_name-${{ env.VERSION }}-${{ matrix.target }}"
          mkdir "$dirname"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv "target/${{ matrix.target }}/release/$binary_name.exe" "$dirname"
          mv "target/${{ matrix.target }}/release/$binary_name" "$dirname"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a "$dirname.zip" "$dirname"
            echo "ASSET=$dirname.zip" >> $GITHUB_ENV
          tar -czf "$dirname.tar.gz" "$dirname"
          echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.ASSET }}
